Repository krsi721424/2dGame, pull requests merged in 2020-01, with the labels that each got.

#3 Content and menu graphic states.
  2DGame/2DGame/Content/SpriteSheet.cs
  2DGame/2DGame/GameStates/GameState.cs
  2DGame/2DGame/GameStates/GameStateManager.cs
  2DGame/2DGame/GameStates/States/PlayingState.cs
Labels: code review

#7 levelObjects
  .DS_Store
  2DGame/.DS_Store
  2DGame/2DGame/LevelObjects/Animation/AnimatedGameObject.cs
  2DGame/2DGame/LevelObjects/Animation/Animation.cs
  2DGame/2DGame/LevelObjects/Enemies/FallowingEnemy.cs
  2DGame/2DGame/LevelObjects/Player.cs
  2DGame/2DGame/LevelObjects/Tile.cs
Labels: enhancement

#2 Piotr
  2DGame/2DGame/2DGame.csproj
  2DGame/2DGame/Levels/Level.cs
  2DGame/2DGame/PathFinding/MatrixNode.cs
Labels: conflicts
